apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pv.yaml
- deploy.yaml
- service.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    prometheus-k8s: "true"
commonLabels:
  prometheus-k8s-cleanup: "true"
configMapGenerator:
- files:
  - ./conf/prometheus.yml
  name: prometheus-k8s-config
namespace: monitoring