---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-k8s-storage-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /storage/k8s1/prometheus/storage
    type: ""
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: prometheus-k8s-storage-pvc
    namespace: monitoring
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

# Creacion de volume claims
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-k8s-storage-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  volumeName: prometheus-k8s-storage-pv