---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-k8s-svc
  labels:
    app: prometheus-k8s
spec:
  ports:
  - name: prometheus
    port: 9090
    targetPort: 9090
  selector:
    app: prometheus-k8s
  type: ClusterIP