apiVersion: v1
kind: Service
metadata:
  name: main-collector-prometheus
  namespace: opentelemetry
spec:
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/name: main-collector
  type: ClusterIP