# sidecar.yml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: sidecar
  namespace: app
spec:
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    
    processors:
      batch:
    
    exporters:
      logging:
      otlp:
        endpoint: "http://main-collector.opentelemetry.svc.cluster.local:4317"
        tls:
          insecure: true
    
    extensions:
      health_check:

    service:
      telemetry:
        logs:
          level: "debug"
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [otlp]